var bar1 = { lat: 41.63191094818953, 
             lng: 2.1632887423038483,
             name: 'La Cope', 
             img1:'img/detallebar.jpeg',
             img2:'img/detallebar2.jpeg',
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396342351',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'destacadomes.html'
             };
var bar2 = { lat: 41.63329803376949,  
             lng: 2.1633319929242134,
             name: 'El Centru', 
             img1:'img/cafedelcentre.jpg',
             img2:'img/detallebar3.jpeg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396554351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar1.html'
             };
var bar3 = { lat: 41.633179668408125,  
             lng: 2.1627046912908554, 
             name: 'Festuk Café', 
             img1:'img/detallebar2.jpeg',
             img2:'img/detallebar3.jpeg', 
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396542549',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'bar2.html'
             };
var bar4 =  { lat: 41.63086476681103,  
             lng: 2.1643247455358505, 
             name: 'Les cases dels mestres', 
             img1:'img/detallebar2.jpeg',
             img2:'img/detallebar4.jpg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar1.html'
             };
var bar5 =  { lat: 41.6302355153933,  
             lng: 2.1654237806797028, 
             name: 'Iseo', 
             img1:'img/detallebar3.jpeg',
             img2:'img/detallebar2.jpeg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'bar3.html'
             };
var bar6 =  { lat: 41.62817453698642,  
             lng: 2.167350947856903, 
             name: 'Can Cortada', 
             img1:'img/detallebar2.jpeg',
             img2:'img/detallebar.jpg',
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar1.html'
             };
var bar7 =  { lat: 41.63028764045204,
             lng: 2.171221375465393,
             name: 'Il Caffe di Rommy', 
             img1:'img/detallebar2.jpeg',
             img2:'img/detallebar3.jpg',
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'bar2.html'
             };
var bar8 =  { lat: 41.62485437873858,  
             lng: 2.1708592772483826, 
             name: 'El Café del Caprabo', 
             img1:'img/detallebar.jpeg',
             img2:'img/detallebar2.jpg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar3.html'
             };
var bar9 =  { lat: 41.626241808656864,  
             lng: 2.1674099564552307, 
             name: 'Bar Oeste', 
             img1:'img/detallebar4.jpeg',
             img2:'img/detallebar.jpg',
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar1.html'
             };
var bar10 =  { lat: 41.63415580362854,  
             lng: 2.16243177652359, 
             name: 'El café de la vila', 
             img1:'img/detallebar2.jpeg',
             img2:'img/detallebar4.jpg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'bar2.html'
             };
var bar11 =  { lat: 41.63165290101946,  
             lng: 2.1671149134635925, 
             name: 'Bar Can Fanga', 
             img1:'img/detallebar.jpeg',
             img2:'img/detallebar3.jpg',
             desc: 'Nunc ante quam, malesuada et rhoncus quis, hendrerit id orci. Cras purus ipsum, semper eget sollicitudin vel, molestie mattis nibh.',
             adress: 'Av Sabadell num:39 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Fruta variada',
             tapa2: 'Tabla de Quesos',
             tapa3: 'Pinchos',
             url: 'bar3.html'
             };
var bar12 =  { lat: 41.630440005766665,  
             lng: 2.1679772436618805, 
             name: 'La Pelleria', 
             img1:'img/detallebar.jpeg',
             img2:'img/detallebar4.jpg',
             desc: 'Vestibulum porta vel quam sit amet pulvinar.Quisque ac dictum augue. Donec et nisl tempus, vulputate diam sit amet, pretium ipsum. Nullam ultricies pellentesque ipsum.',
             adress: 'C/ Montserrat num:2 Caldes de Montbui',
             telf: '+0034396542351',
             tapa1: 'Calamares en su tinta',
             tapa2: 'Bravas no picantes',
             tapa3: 'Paella Gallega',
             url: 'bar1.html'
             };




var bares = [bar1,bar2,bar3,bar4,bar5,bar6,bar7,bar8,bar9,bar10,bar11,bar12];